apiVersion: v1
kind: Service
metadata:
  name: parse-csv-service
  namespace: med
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app: parse-csv
